### PR TITLE
fix: readonly value can't change

### PR DESCRIPTION
**Pull request by prakash-nc**
Throwing an error when using in block content.

image

Here is the example code to verify
`/* @ts-ignore */

import React from 'react';
import { FiSun } from 'react-icons/fi';
import { FaHighlighter } from 'react-icons/fa';
import { SecondaryThemePalette } from '@uhev/content-sanity-shared/dist/schemas/objects/theme'

const TextColorRender = (props) => {
  const { color = { value: "#ffffff" }, children } = props;
  return <span style={{
    backgroundColor: color.value,
    border: "none",
    fontFamily: "JennaSue",
    padding: "0.2rem",
  }}>{children}</span>;
};

const TextHighlighted = (props, backgroundColor, fontFamily) => {
  return <span style={{ backgroundColor, fontFamily }}>{props.children}</span>;
};

export default {
  title: 'Block Content',
  name: 'blockContent',
  type: 'array',
  of: [
    {
      title: 'Block',
      type: 'block',
      lists: [{ title: 'Bullet', value: 'bullet' }],
      // Marks let you mark up inline text in the block editor.
      marks: {
        // Decorators usually describe a single property – e.g. a typographic
        // preference or highlighting by editors.
        decorators: [
          { title: 'Strong', value: 'strong' },
          { title: 'Emphasis', value: 'em' },
          { title: 'Jane', value: 'jane' },
          {
            title: 'Highlighted',
            value: 'highlighted',
            blockEditor: {
              icon: FiSun,
              render: (props) => TextHighlighted(props, '#FFFFFF', 'JennaSue'),
            },
          },
        ],
        // Annotations can be any object structure – e.g. a link or a footnote.
        annotations: [
          {
            name: 'Highlighter',
            type: 'object',
            title: 'Highlighter',
            fields: [
              {
                name: "color",
                title: "Color",
                type: 'colorlist', // required
                options: {
                  borderradius: {
                    outer: '100%',
                    inner: '100%',
                  },
                  list: [...SecondaryThemePalette],
                },
              }
            ],
            blockEditor: {
              icon: FaHighlighter,
              render: (props) => TextColorRender(props),
            },
          },
        ],
      },
    },
  ],
};
`

### CODE REVIEW

**Comment by KimPaow** [comment]
Nice catch, @prakash-nc. Looks like that line of code can be safely removed but I'll take a closer look later before merging this in if there are no problems.

**Comment by prakashio** [comment]
> Nice catch, @prakash-nc. Looks like that line of code can be safely removed but I'll take a closer look later before merging this in if there are no problems.

Thanks, @KimPaow

**Comment by prakash-nc** [comment]
Thanks @KimPaow

**Comment by prakash-nc** [comment]
Hi @KimPaow, Could you please look into this.

**Comment by KimPaow** [comment]
@prakash-nc Sorry for the delay, I've been swamped, I will take a look at this today.

**Comment by KimPaow** [comment]
Merged and 2.0.2 published, thanks for contributing!

**Pull request merged**
